services:
  gateway:
    healthcheck:
      disable: true
    labels:
      traefik.enable: "true"
      traefik.hostname: deploy
    environment:
      GATEWAY_SYSTEM_NAME: deploy
      GATEWAY_PUBLIC_HTTP_PORT: 80
      GATEWAY_PUBLIC_HTTPS_PORT: 443
      GATEWAY_PUBLIC_ADDRESS: deploy.docker.bwdesigngroup.net
    networks:
      - default
      - proxy

networks:
  default:
  proxy:
    external: true
    name: proxy
