name: auto-deploy
on:
  push:
    branches: [ deploy-on-server ]
jobs:
  Deploy:
    name: Spenny
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: deployer
        run: |
          mkdir ignition-data
          chmod -R g+w ignition-data
          docker-compose up -d
